workflow:
  # Any of the rule must match to attempt to create a pipeline.
  # So list any additional relevant CI_PIPELINE_SOURCE as needed.
  #   - https://docs.gitlab.com/ci/jobs/job_rules/#ci_pipeline_source-predefined-variable
  # Jobs should additionally define `rules` as needed, or `extend` from templates that define rules.
  rules:
    # Merge requests
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Pipeline schedules
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    # Manually triggered pipelines
    - if: $CI_PIPELINE_SOURCE == 'web'
    # Additionally, always attempt on tags
    - if: $CI_COMMIT_TAG
    # And always attempt on main branch commit events (i.e. merge and push)
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Stages define “buckets” that run in order, in which jobs can run in parallel.
# Usage of stages can help define dependencies and ordering between jobs, but using the `needs` keyword is preferred instead.
# Stages that are not used in a pipeline are not exposed.
stages:
  - deploy
  - scheduled

# We include all of the CtrlOS independent gitlab-ci YAML files.
include:
  - local: "ctrlos/ci/gitlab-ci/*.yml"
