update_channel:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: "$CTRLOS_CHANNEL_AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$CTRLOS_CHANNEL_AWS_SECRET_ACCESS_KEY"
    AWS_REGION: "$CTRLOS_CHANNEL_AWS_REGION"
    AWS_ENDPOINT_URL: "$CTRLOS_CHANNEL_AWS_ENDPOINT_URL"
  script:
    - mkdir -p tarball/
    - nix shell nixpkgs#{gitMinimal,xz} --command sh -c
      'git archive --format=tar --prefix=ctrlos-$(git rev-parse HEAD)/ HEAD | xz -v -9 > tarball/ctrlos-$(git rev-parse HEAD).tar.xz'
    - nix shell github:cyberus-technology/s3-nix-channel --command sh -c
      "s3-nix-channel-upload publish $CTRLOS_CHANNEL_BUCKET ctrlos-24.05 tarball/*"
  rules:
    - if: '$CI_COMMIT_BRANCH == "ctrlos-24.05"'
  artifacts:
    paths:
      - tarball/
  tags:
    - nix

